### ISSUE TITLE
Onboard Project AICoE

### ISSUE THREAD

**Issue by Shreyanand** [operate-first/continuous-delivery#8]
**Do you need a project on AICoE org in Quay.io?**
Yes, for the time-series project image.

**Detail required for the setup:**
Please describe the following requirements.
_Repository Name_: time-series
_GitHub Repository associated_: https://github.com/aicoe-aiops/time-series
_UserId of users requiring Admin Access_: shanand

**Comment by harshad16** [comment]
The repository is now available: https://quay.io/repository/aicoe/time-series
Also given `shanand` admin access to the repo. 
please close the issue, if this suffice.

**Comment by Shreyanand** [comment]
This looks good! Thanks. Do I need to make any changes in quay for the automatic trigger to work? I'm going to use this config: 
```
check:
  - thoth-precommit
  - thoth-build


build:
  build-stratergy: Source
  build-source-script: "image:///opt/app-root/builder"
  base-image: quay.io/thoth-station/s2i-custom-notebook:latest
  custom-tag: latest
  registry: quay.io
  registry-org: aicoe
  registry-project: time-series
  registry-secret: aicoe-pusher-secret
```
